#BNF+IAT 1.0 UTF-8;
!grammar goto;
!slot <go>;
!start  <operation>;

<operation>:<go>;
<go>:往前走!id(2000)|向前走!id(2000)|过来!id(2000)
        |往后走!id(2001)|向后走!id(2001)|退后!id(2001)
        |左转!id(2002)|右转!id(2003)
       |点位一!id(2004)|点位二!id(2005)|点位三!id(2006)
       |漫游!id(2007)|停下来!id(2008);
